server:
  port: 8093



spring:
  application:
    name: feign-client

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/