
spring:
  application:
    name: zhiyin-ranker
    version: 0.0.1
#  profiles:
#    active: product
#    active: test

server:
#  contextPath: /${spring.application.name}
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    home-page-url-path: ${server.contextPath}/
    statusPageUrlPath: ${server.contextPath}/info
    healthCheckUrlPath: ${server.contextPath}/health

#management.security.enabled=false
#security.basic.enabled=false

resource:
  directory: src/main/resources/
captcha:
  directory:
    static/app/dist/img/
  destination:
    src/main/resources/static/app/dist/img

## acutor 设置
management:
  port: 18081
  address: 127.0.0.1
  security:
    enabled: false
    role: SUPERUSER

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin