
spring:
  application:
    name: ese-demo
    version: 0.0.1

server:
#  contextPath: /${spring.application.name}
  port: 8180


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    home-page-url-path: ${server.contextPath}/
    statusPageUrlPath: ${server.contextPath}/info
    healthCheckUrlPath: ${server.contextPath}/health

logging:
  file: logs/${spring.application.name}.log


#management.security.enabled=false
#security.basic.enabled=false