// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.xxx.demo.demo;

public abstract class Callback_MyService_hello
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<com.xxx.demo.demo.Order>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        MyServicePrxHelper.__hello_completed(this, __result);
    }
}
