// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.xxx.demo.demo;

public final class MyServicePrxHelper extends Ice.ObjectPrxHelperBase implements MyServicePrx
{
    private static final String __hello_name = "hello";

    public Order hello(Order in)
    {
        return hello(in, null, false);
    }

    public Order hello(Order in, java.util.Map<String, String> __ctx)
    {
        return hello(in, __ctx, true);
    }

    private Order hello(Order in, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__hello_name);
        return end_hello(begin_hello(in, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_hello(Order in)
    {
        return begin_hello(in, null, false, false, null);
    }

    public Ice.AsyncResult begin_hello(Order in, java.util.Map<String, String> __ctx)
    {
        return begin_hello(in, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_hello(Order in, Ice.Callback __cb)
    {
        return begin_hello(in, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_hello(Order in, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_hello(in, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_hello(Order in, Callback_MyService_hello __cb)
    {
        return begin_hello(in, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_hello(Order in, java.util.Map<String, String> __ctx, Callback_MyService_hello __cb)
    {
        return begin_hello(in, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_hello(Order in, 
                                       IceInternal.Functional_GenericCallback1<Order> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_hello(in, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_hello(Order in, 
                                       IceInternal.Functional_GenericCallback1<Order> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_hello(in, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_hello(Order in, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<Order> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_hello(in, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_hello(Order in, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<Order> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_hello(in, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_hello(Order in, 
                                        java.util.Map<String, String> __ctx, 
                                        boolean __explicitCtx, 
                                        boolean __synchronous, 
                                        IceInternal.Functional_GenericCallback1<Order> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_hello(in, __ctx, __explicitCtx, __synchronous, 
                           new IceInternal.Functional_TwowayCallbackArg1<com.xxx.demo.demo.Order>(__responseCb, __exceptionCb, __sentCb)
                               {
                                   public final void __completed(Ice.AsyncResult __result)
                                   {
                                       MyServicePrxHelper.__hello_completed(this, __result);
                                   }
                               });
    }

    private Ice.AsyncResult begin_hello(Order in, 
                                        java.util.Map<String, String> __ctx, 
                                        boolean __explicitCtx, 
                                        boolean __synchronous, 
                                        IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__hello_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__hello_name, __cb);
        try
        {
            __result.prepare(__hello_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            Order.__write(__os, in);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public Order end_hello(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __hello_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            Order __ret = null;
            __ret = Order.__read(__is, __ret);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __hello_completed(Ice.TwowayCallbackArg1<Order> __cb, Ice.AsyncResult __result)
    {
        com.xxx.demo.demo.MyServicePrx __proxy = (com.xxx.demo.demo.MyServicePrx)__result.getProxy();
        Order __ret = null;
        try
        {
            __ret = __proxy.end_hello(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    public static MyServicePrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), MyServicePrx.class, MyServicePrxHelper.class);
    }

    public static MyServicePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), MyServicePrx.class, MyServicePrxHelper.class);
    }

    public static MyServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), MyServicePrx.class, MyServicePrxHelper.class);
    }

    public static MyServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), MyServicePrx.class, MyServicePrxHelper.class);
    }

    public static MyServicePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, MyServicePrx.class, MyServicePrxHelper.class);
    }

    public static MyServicePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, MyServicePrx.class, MyServicePrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::demo::MyService"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, MyServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static MyServicePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            MyServicePrxHelper result = new MyServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
