// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.xxx.demo.demo;

public final class MyServicePrxHolder
{
    public
    MyServicePrxHolder()
    {
    }

    public
    MyServicePrxHolder(MyServicePrx value)
    {
        this.value = value;
    }

    public MyServicePrx value;
}
