// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.xxx.demo.demo;

public interface MyServicePrx extends Ice.ObjectPrx
{
    public Order hello(Order in);

    public Order hello(Order in, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_hello(Order in);

    public Ice.AsyncResult begin_hello(Order in, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_hello(Order in, Ice.Callback __cb);

    public Ice.AsyncResult begin_hello(Order in, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_hello(Order in, Callback_MyService_hello __cb);

    public Ice.AsyncResult begin_hello(Order in, java.util.Map<String, String> __ctx, Callback_MyService_hello __cb);

    public Ice.AsyncResult begin_hello(Order in, 
                                       IceInternal.Functional_GenericCallback1<Order> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_hello(Order in, 
                                       IceInternal.Functional_GenericCallback1<Order> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_hello(Order in, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<Order> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_hello(Order in, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<Order> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Order end_hello(Ice.AsyncResult __result);
}
