server:
  port: 10000




spring:
  application:
    name: zuul-server


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  host:
    max-per-route-connections: 200
    max-total-connections: 200
sidecar:
  port: 8000